insert into artist (name, city, state, phone, genres, image_link, facebook_link, seeking_venue, seeking_description) values ('Guns N Petals', 'San Francisc', 'CA', '326-123-5000', 'Rock n Roll', 'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80', 'https://www.facebook.com/GunsNPetals', 'True', 'Looking for shows to perform at in the San Francisco Bay Area!');
insert into artist (name, city, state, phone, genres, image_link, facebook_link, seeking_venue) values ('Matt Quevedo', 'New York', 'NY', '300-400-5000', 'Jazz', 'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80', 'https://www.facebook.com/mattquevedo923251523', 'False');
insert into artist (name, city, state, phone, genres, image_link, seeking_venue) values ('The Wild Sax Band', 'San Francisc', 'CA', '432-325-5432', 'Jazz, Classical', 'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80', 'False');




insert into venue (name, city, state, phone, genres, image_link, facebook_link, website, seeking_talent, seeking_description, address) values ('The Musical Hop', 'San Francisco', 'CA', '123-123-1234', 'Jazz, Reggae, Swing, Classical, Folk', 'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60', 'https://www.facebook.com/TheMusicalHop', 'https://www.themusicalhop.com', 'True', 'We are on the lookout for a local artist to play every two weeks. Please call us.', '1015 Folsom Street');

insert into venue (name, city, state, phone, genres, image_link, facebook_link, website, seeking_talent, address) values ('The Dueling Pianos Bar', 'New York', 'NY', '914-003-1132', 'Classical, R&B, Hip-Hop', 'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80', 'https://www.facebook.com/theduelingpianos', 'https://www.theduelingpianos.com', 'False', '335 Delancey Street');

insert into venue (name, city, state, phone, genres, image_link, facebook_link, website, seeking_talent, address) values ('Park Square Live Music & Coffee', 'San Francisco', 'CA', '415-000-1234', 'Rock n Roll, Jazz, Classical, Folkp', 'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80', 'https://www.facebook.com/ParkSquareLiveMusicAndCoffee', 'https://www.parksquarelivemusicandcoffee.com', 'False', '34 Whiskey Moore Ave');