"""empty message

Revision ID: 21fb810fe0a6
Revises: 89d522b8778a
Create Date: 2022-08-06 16:41:18.685016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21fb810fe0a6'
down_revision = '89d522b8778a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('show', sa.Column('id', sa.Integer(), nullable=False))
    # op.alter_column('show', 'start_time',
    #            existing_type=postgresql.TIMESTAMP(),
    #            nullable=True)
    # ### end Alembic commands ###
    None

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
