"""empty message

Revision ID: 318bcaad04da
Revises: 51f36bb2010f
Create Date: 2022-08-06 19:16:24.112728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318bcaad04da'
down_revision = '51f36bb2010f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'past_shows_count')
    # ### end Alembic commands ###
