"""empty message

Revision ID: 51f36bb2010f
Revises: 50ee26989b78
Create Date: 2022-08-06 19:15:21.056041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f36bb2010f'
down_revision = '50ee26989b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'upcoming_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
