"""empty message

Revision ID: fdac13be22a0
Revises: 10430839bb78
Create Date: 2022-08-06 11:45:50.608705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdac13be22a0'
down_revision = '10430839bb78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('id', sa.Integer()))
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
